exclude: |
  (?x)
  # Maybe reactivate this when all README files include prettier ignore tags?
  ^README\.rst$|
  # You don't usually want a bot to modify your legal texts
  (LICENSE.*|COPYING.*)

default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        exclude: ^migrations/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.5.1"
    hooks:
      - id: prettier
        exclude: ^dist/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v6.8.0
    hooks:
      - id: eslint
        verbose: true
        args:
          - --color
          - --fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^README\.rst$|\.pot?$
      - id: end-of-file-fixer
        exclude: ^README\.rst$|\.pot?$
      - id: debug-statements
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
        exclude: ^README\.rst$|^docs/.*\.rst$
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: flake8 except __init__.py
        exclude: (^__init__\.py$|^migrations/)
        additional_dependencies: ["flake8-bugbear==24.8.19"]

      - id: flake8
        name: flake8 only __init__.py
        args: ["--extend-ignore=F401"]
        files: ^__init__\.py$
        additional_dependencies: ["flake8-bugbear==24.8.19"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.26.2
    hooks:
      - id: pyupgrade
        exclude: ^migrations/

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: isort except __init__.py
        exclude: (^__init__\.py$|^migrations/)

  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.2.1
    hooks:
      - id: check-untracked-migrations
