# Generated by Django 5.2.2 on 2025-06-14 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "_otp",
                    models.CharField(
                        db_column="otp",
                        help_text="The Protected OTP instance.",
                        max_length=255,
                        verbose_name="OTP",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="The OTP key used for authentication.",
                        max_length=255,
                        verbose_name="Key",
                    ),
                ),
                (
                    "otp_type",
                    models.CharField(
                        choices=[
                            ("sms", "SMS-based OTP"),
                            ("email", "Email-based OTP"),
                        ],
                        help_text="The type of OTP key. This can be Email, SMS, Registration, or Login.",
                        max_length=50,
                        verbose_name="OTP Type",
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The date and time when the OTP key expires.(in seconds)",
                        null=True,
                        verbose_name="Expired At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified")],
                        default="pending",
                        help_text="The status of the OTP key, e.g., Pending & Verified.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when the OTP key was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time when the OTP key was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user associated with this OTP key.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
    ]
