# Generated by Django 5.2.2 on 2025-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="otp_type",
            field=models.CharField(
                choices=[
                    ("email", "Email Verification OTP"),
                    ("phone", "Phone Verification OTP"),
                    ("forgot-password", "Forgot Password OTP"),
                    ("reset-password", "Reset Password OTP"),
                    ("two-factor-authentication", "Two Factor Authentication OTP"),
                ],
                help_text="The type of OTP key. This can be Email, SMS, Registration, or Login.",
                max_length=50,
                verbose_name="OTP Type",
            ),
        ),
    ]
