# Generated by Django 5.2.2 on 2025-06-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_otp_otp_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="_otp",
            field=models.CharField(
                db_column="otp",
                editable=False,
                help_text="The Protected OTP instance.",
                max_length=255,
                verbose_name="OTP",
            ),
        ),
    ]
