name: Publish Python 🐍 distribution 📦 to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write # required for OIDC
  contents: read # to fetch code

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build package
        run: |
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v0.1
        with:
          # No need for a password if using PyPI Trusted Publisher with OIDC
          skip-existing: true
